fsprojects/ProjectScaffold

paket.lock
tests/FSharp.ProjectTemplate.Tests/FSharp.ProjectTemplate.Tests.fsproj

Including latest FSharp.Formatting

Update all dependencies

---

build.template

Issue #120 Use the complete path to consider the name of AssemblyInfo.cs

---

docs/tools/generate.template
paket.lock

Reverts fsprojects/ProjectScaffold#138

Revert "Update F# Formatting and reference via load script"

---

paket.dependencies
src/FSharp.ProjectTemplate/FSharp.ProjectTemplate.fsproj
src/FSharp.ProjectTemplate/paket.references
tests/FSharp.ProjectTemplate.Tests/FSharp.ProjectTemplate.Tests.fsproj
tests/FSharp.ProjectTemplate.Tests/paket.references

Revert due to stackoverflow exceptions ref #144

Reverted Fsharp.core from nuget package

---

build.template

Rough support for Vb.net projects

Add vb.net support

---

build.template

Simplifying AssemblyInfo.fs path

---

paket.dependencies

This is a temporary fix for #156 until the problem with FSharp.Formatting is fixed (see https://github.com/tpetricek/FSharp.Formatting/issues/277)

Temporay fix for #156

---

docs/tools/generate.template

See tpetricek/FSharp.Formatting#281.

fix for tpetricek/FSharp.Formatting#281

---

docs/content/index.md

Improved descriptions and instructions

Improved descriptions and instructions

---

src/FSharp.ProjectTemplate/FSharp.ProjectTemplate.fsproj

From here: http://www.jefclaes.be/2015/04/finding-unused-code-f.html
What do people think of including this as default?

Set compiler flag for unused code

---

build.sh

Use fsiargs properly on mono
Only use a loader on mono by using a function
@cdrnet

Updates for build.sh

---

build.template

Use FAKE's watcher

---

docs/tools/templates/template.cshtml

Update Html5Shiv script to a CDN

---

src/FSharp.ProjectTemplate/FSharp.ProjectTemplate.fsproj
tests/FSharp.ProjectTemplate.Tests/FSharp.ProjectTemplate.Tests.fsproj

removed xml doc from Debug target and test project

---

.gitattributes

Because some of us do use VB still :)

Add *.vb files to .gitattributes

---

.travis.yml

Created a fresh project, pushed, travis threw this error for build.sh:
http://stackoverflow.com/questions/33820638/travis-ci-gradlew-permission-denied

permit build.sh to execute in .travis.yml

---

src/FSharp.ProjectTemplate/paket.template

nuget.org has title property in package properties.

Added title to paket.template

---

init.fsx
src/FSharp.ProjectTemplate/paket.template

I noticed that the **paket.template** wasn't properly populated by **##GitName##** value so here is the fix.

Add replace for GitName

---

build.template

Hi,
I append "configuration" with "Release" symbol bound.
We are using with configurable for building binaries, switch between "Debug" and "Release".

Support configuration variable.

---

index.html
writing-docs.html

also added missing steps in getting started

docs for GH page doc source change

---

writing-docs.html

@pblasucci updated writing-docs page to refer to docsrc folder

update writing-docs with docsrc folder

---

index.html

@pblasucci added section to github.io page

add Migrating an Existing Project doc

---

src/FSharp.ProjectTemplate/paket.template

This was basically the one thing I had to change in order to deploy my new NuGet package.

Update default paket copyright year.

---

.paket/Paket.Restore.targets
build.cmd
build.proj
build.sh

Also updates build.sh to call `fake run init.fsx`
Co-authored-by: Jeff Boek <jeff@jeffboek.com>

Updates dotnet fake to fake
