fsprojects/ProjectScaffold

docs/tools/generate.template
paket.lock

The most recent version of F# Formatting includes a load script, which makes referencing the library easier and also avoids future incompatibilities when we change the dependencies (previously, you had to add `#I "...whatever_new_dependency..."`, which is now done in the load script.

Update F# Formatting and reference via load script

---

build.template
docs/tools/generate.template
nuget/FSharp.ProjectTemplate.nuspec
paket.lock

For details see #119.
I also added a workaround for nuget package creation on mono. (so `build NuGet` works).
Please tell me if you don't want it and I will remove the commit.
Maybe you should now enable both in travis?

Improve mono support.

---

docs/tools/generate.template

Adding option to manually specify dlls to generate docs for in generate.fsx to provide upgrade path for
older projects.
Adresses the upgrade issues pointed out by @tpetricek in #153

Adding backwards compatibility with previous scaffold conventions

---

docs/tools/generate.template

to apply correct language specific template.
Without this change, `docs/tools/templates/template.cshtml` has been applied to all content files even though these files are placed in the language specific directory, such as `docs/content/ja`.

Fix docs/tools/generate.template

---

build.template

This basically ensures we don't get caught by surprise when the documentation generation starts failing (#156, #159 ,... )

Always build docs to test the documentation generation on the CI

---

.gitignore

Based on [this suggestion][1], certain Visual Studio data is moving into a .vs directory. The contents aren't important for source control, so add it to the `.gitignore` file.
[1]: https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6079923-store-project-related-information-in-vs-folder-to

Added .vs directory to gitignore

---

init.fsx

During the init phase GitName was not being set even if a GitName distinct from ProjectName was provided. The PR addresses that.

Set GitName to value provided during init

---

.paket/paket.targets

on OS X and Mono, xbuild will fail if exe path includes whitespace.

Fix build exe path which includes whitespace

---

.gitignore
init.fsx

+ extended `init.fsx` to handle git repo deletion/creation/origin-setting
+ init script deletes `.git` if it exists _and_ the push origin is `fsprojects/ProjectScaffold`
+ init script prompts the user for whether or not to create a local git repo
+ init script prompts user for remote url; if given sets origin (only called if local repo is created)
+ updated git to ignore .mdb (Mono debug?) files
(P.S. Sorry the line endings got screwed up)

Extended init script to manage git repo

---

build.template

The remote is selected based on the location that the docs are set to be
pushed to. If it cannot be found locally, then the docs location (with
https) is used.

Prompt for username/password, and choose remote

---

docs/tools/generate.template

FSharp.Formatting, FSharp.Compiler.Service and FAKE have a special relation going on, causing newer FSharp.Formatting builds to fail generating documentation with this template. See https://github.com/tpetricek/FSharp.Formatting/issues/337#issuecomment-147828568 for more info.

Fix FSharp.Formatting and FSharp.Compiler.Service

---

paket.dependencies

NUnit3 changes the console-runners name to console-runner3 and modifies the command line parameters making the Fake task inoperable until support is added to Fake.

Update paket.dependencies to keep NUnit version < 3

---

build.template

Should fix https://github.com/mathnet/mathnet-numerics/issues/346, https://github.com/tpetricek/FSharp.Formatting/issues/328, https://github.com/tpetricek/FSharp.Formatting/issues/356 and https://github.com/fsprojects/ProjectScaffold/issues/210.

use FAKE for documentation generation.

---

build.template

I think the build target KeepRunning should rely on GenerateHelpDebug instead of GenerateHelp.
In this way `generateHelp'` is called with the debug flag.

GenerateHelpDebug when KeepRunning

---

build.template

Sometimes the projects compiled would benefit from knowing they are compiled in Mono too.

Propagate #define MONO to the projects too

---

build.sh

A previous commit (b612328) moved the location of FAKE.exe around but
missed updating every reference to it in build.sh. (This is why the Mono build is broken in CI).
This should make sure that doesn't happen again.

Parameterize Paket/FAKE binaries used in build.sh

---

build.sh

One of the most common reasons for the Paket bootstrapper to fail on Linux is if the Mono installation is brand-new -- because out of the box, Mono does not trust *any* X.509 root certificates. Therefore, GitHub's SSL certificate won't be trusted and Paket won't be downloaded.
The fix most often recommended is to run:
mozroots --import --sync
which imports the entire root SSL certificate store trusted by the Mozilla project. This is over 100 certificates, so not everyone will want to run this command. (And we certainly shouldn't be running it for them.) But we should suggest it, because not everyone knows about the mozroots command. In particular, if someone is new to F# and Mono, this suggestion might save them hours of frustrated Google searches.
Note that the Mono project has said (in …

Don't run mozroots automatically; ask instead

---

docs/content/release-process.md

The current ProjectScaffold version uses Paket groups. The change was missing in the release documentation.

FIX: Path to FAKE.exe corrected in documentation to create release.cmd

---

paket.dependencies
paket.lock
src/FSharp.ProjectTemplate/App.config
src/FSharp.ProjectTemplate/FSharp.ProjectTemplate.fsproj
src/FSharp.ProjectTemplate/paket.references
tests/FSharp.ProjectTemplate.Tests/App.config
tests/FSharp.ProjectTemplate.Tests/FSharp.ProjectTemplate.Tests.fsproj
tests/FSharp.ProjectTemplate.Tests/paket.references

* Remove FSharp.Core direct references from fsproj files
* Add FSharp.Core nuget reference and force redirects
* Add App.config so paket can add redirects
Note that Paket has automatically rearranged a bit in the project files and removed the patch version numbers from the lock file.

Let Paket manage FSharp.Core

---

build.sh

In https://gitter.im/ionide/ionide-project, someone was complaining of being unable to run the FAKE build script inside Ionide because his shell was set to Dash, not Bash. And that started me thinking: does the `build.sh` in Project Scaffold *have* to use Bash? I know the shebang on the first line specifies Bash, and Bash is considered an essential package (therefore always installed) on Debian-based systems... but will Bash *always* be installed on every system that the `build.sh` script might run on?
So I set out to investigate if "[bashisms](http://mywiki.wooledge.org/Bashism)" could be removed from the `build.sh` script. There were three bashisms: the `set -o pipefail` line (not available in Dash), the use of the `[[` syntax for `test` (also not available in Dash), and the use of …

Make build.sh runnable by (almost) any shell

---

build.template

Hi, 
With current **Release targets sort order** when I call target release on **LocalBuild** my dependency graph looks like 
```
Building project with version: LocalBuild
Shortened DependencyGraph for Target Release:
<== Release
<== ReleaseDocs
<== All
<== GenerateDocs
<== GenerateReferenceDocs
<== RunTests
<== CopyBinaries
<== Build
<== AssemblyInfo
<== Clean
<== GenerateHelp
<== CleanDocs
<== PublishNuget
<== BuildPackage
<== NuGet
The resulting target order is:
- Clean
- AssemblyInfo
- Build
- CopyBinaries
- RunTests
- CleanDocs
- GenerateHelp
- GenerateReferenceDocs
- GenerateDocs
- All
- ReleaseDocs
- NuGet
- BuildPackage
- PublishNuget
- Release
```
When I build on my **jenkins server** my dependency graph looks like 
```
Building project with version:
Shortened DependencyGraph for …
```

Fix ReleaseDocs before Build

---

build.template
docs/tools/generate.template
init.fsx
src/FSharp.ProjectTemplate/paket.template

The company I am working for has his own private Github so the root domain urls aren't the same.
I would be nice to have the possibility to set those urls on scaffold init ?

Parameterize Git url and Git raw url

---

build.sh

Fixes error, when the build script is invoked using a path containing whitespaces:
```
~ $ ./Internal\ Projects/fsharp/HParser/build.sh
Cannot open assembly '.paket/paket.bootstrapper.exe': Datei oder Verzeichnis nicht gefunden.
```

Handle directories containing whitespace properly

---

build.template
init.fsx

I forgot to add a slash '/' for **gitHome** yesterday
I introduced a way to normalize input to avoid (in my case) bad formatting.

Fix gitHome url, introduce normalization for input

---

CheckFSharpInstallation.fsproj
init.fsx

If F# is not installed (say a Linux user has installed the `mono-complete` package, mistakenly thinking that F# was included in `mono-complete`), the error message that the user will see when he runs `build.sh` or `build.cmd` is "Target named 'Rebuild' not found in the project". Instead, we should check (once) in `init.fsx` to make sure that F# is properly installed, and give a clearer error message if it isn't.
This should fix #253.

Check that F# is installed in init.fsx

---

build.template

When most people clone ProjectScaffold, they're just getting started with their project, not getting ready to release it. It would be more useful to let the default build configuration default to `Debug`, not `Release`.

Build configuration should default to Debug

---

paket.dependencies
paket.lock
src/FSharp.ProjectTemplate/App.config
src/FSharp.ProjectTemplate/FSharp.ProjectTemplate.fsproj
tests/FSharp.ProjectTemplate.Tests/App.config
tests/FSharp.ProjectTemplate.Tests/FSharp.ProjectTemplate.Tests.fsproj

Here are some various fixes
Most notably it adds these framework restrictions to prevent so many libraries being downloaded.  I think this is OK as we are not yet enabling .NET Standard now .NET Portable development with the scaffold?
frameworks: net45, net46, net461, net462

Various fixes

---

build.template

Am reverting as ``build Release`` should turn on release mode

Revert "Build configuration should default to Debug"

---

build.template

See https://github.com/fsprojects/Paket/issues/1817, this allows the use of ``paket config add-token`` on ``https://www.nuget.org``.  Without the key isn't found, see https://github.com/fsprojects/Paket/issues/1817
paket config add-token "https://www.nuget.org" 4003d786-cc37-4004-bfdf-c4f3e8ef9b3a

Be explicit about publish URL

---

init.fsx

Fixes https://github.com/fsprojects/ProjectScaffold/issues/276. When the ProjectScaffold repo has been cloned via ssh or https the "Initialise git repo" step does not work correctly. This is because the check performed to see if the remote matches the ProjectScaffold repo only tests for the following remote url format:
``http://github.com/fsprojects/ProjectScaffold.git``
This fix adds support for the additional remote url formats:
``https://github.com/fsprojects/ProjectScaffold.git``
and
``git@github.com:fsprojects/ProjectScaffold.git``
to correctly handle when the repo has been cloned by https or ssh.

Clear git history when cloned via ssh or https

---

init.fsx

Fixes #315. When the ProjectScaffold repo is cloned via copy-and-paste from the browser's address bar, its remote ends up looking like https://github.com/fsprojects/ProjectScaffold (without .git at the end). This PR ensures that that URL will be matched when deciding whether to erase ProjectScaffold history in the initial project setup phase.

Clear git history when remote does not end in .git

---

paket.dependencies

When I run `./build.sh` in macos, I got an error:
```sh
Mono.CSharp.InternalErrorException: Failed to import assembly `Argu, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' ---> System.ArgumentException: Value does not fall within the expected range.
```
After digging a while, I find this issue: https://github.com/fsprojects/FSharp.Formatting/issues/412 nothing helped.
But when I git cloned the FSharp.Formating repo and built, it didn't fail, so I upgrade the dep in ProjectScaffold, succeed!

Fix GenerateDoc failed in Mono (macos)

---

build.template

`build <Target>` doesn't work anymore

Fix comment about specifying target
